version: '3'

networks:
  traning-opstella:

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust-loadtest:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://nestjs:3000
    networks:
      - traning-opstella

  worker:
    image: locustio/locust
    volumes:
      - ./locust-loadtest:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    networks:
      - traning-opstella

  nestjs:
    build:
        context: ./nestjs-9.0.0
        dockerfile: Dockerfile
    container_name: nestjs
    # environment:
    #   - "3000:3000"
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - traning-opstella
